nacos:
  config:
    namespace: public
    server-addr: 121.4.49.169:8848
    bootstrap:
      enable: true
      log-enable: true
    data-id: timi
    type: yaml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
  mapperLocations:
    - classpath*:/mapper/**/*.xml
    - classpath*:/modeler-mybatis-mappings/**/*.xml